name: ble_connector
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.22.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.2.0
  json_annotation: ^4.8.1
  logger: ^2.0.1
  rxdart: ^0.27.7
  synchronized: ^3.1.0
  uuid: ^4.5.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
