name: nineti_heimspeicher
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4
  flutter: 3.22.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  ble_connector:
    path: ../ble_connector
  rxdart: ^0.27.7
  logger: ^2.3.0
  provider: ^6.1.2
  equatable: ^2.0.5
  ble_communication:
    path: ../ble_communication
  protobuf: ^2.1.0
  mocktail: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
